# Generated by Django 5.1.2 on 2024-12-02 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id_admin', models.AutoField(primary_key=True, serialize=False)),
                ('nama_admin', models.CharField(max_length=100)),
                ('email_admin', models.EmailField(max_length=254, unique=True)),
                ('password_admin', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GolonganPelanggan',
            fields=[
                ('id_golongan_pelanggan', models.AutoField(primary_key=True, serialize=False)),
                ('kelompok_pelanggan', models.CharField(max_length=100)),
                ('tarif_0_3', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tarif_3_10', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tarif_10_20', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tarif_diatas_20', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Petugas',
            fields=[
                ('id_petugas', models.AutoField(primary_key=True, serialize=False)),
                ('nama_petugas', models.CharField(max_length=100)),
                ('nik_petugas', models.CharField(max_length=20, unique=True)),
                ('jenis_kelamin_petugas', models.CharField(max_length=10)),
                ('alamat_petugas', models.TextField()),
                ('wilayah_penugasan', models.TextField()),
                ('email_petugas', models.EmailField(max_length=50, unique=True)),
                ('no_telepon_petugas', models.CharField(max_length=15)),
                ('password_petugas', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SumberAir',
            fields=[
                ('id_sumber_air', models.AutoField(primary_key=True, serialize=False)),
                ('nama_sumber_air', models.CharField(max_length=100)),
                ('alamat_sumber_air', models.TextField()),
                ('jenis', models.CharField(max_length=50)),
                ('kualitas', models.CharField(max_length=50)),
                ('kapasitas', models.IntegerField()),
                ('status_sumber_air', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Lokasi',
            fields=[
                ('id_lokasi', models.AutoField(primary_key=True, serialize=False)),
                ('nama_lokasi', models.CharField(max_length=50)),
                ('alamat_lokasi', models.TextField()),
                ('jumlah_penduduk', models.IntegerField()),
                ('faktor_tarif', models.DecimalField(decimal_places=2, max_digits=5)),
                ('id_sumber_air', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lokasi', to='AirBersih.sumberair')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('nama_user', models.CharField(max_length=50)),
                ('nik_user', models.CharField(max_length=16, unique=True)),
                ('jenis_kelamin_user', models.CharField(max_length=10)),
                ('alamat_user', models.TextField()),
                ('kecamatan', models.CharField(max_length=50)),
                ('email_user', models.EmailField(max_length=50, unique=True)),
                ('no_telepon_user', models.CharField(max_length=15)),
                ('password_user', models.CharField(max_length=30)),
                ('id_golongan_pelanggan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='AirBersih.golonganpelanggan')),
                ('id_lokasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='AirBersih.lokasi')),
            ],
        ),
        migrations.CreateModel(
            name='Tagihan',
            fields=[
                ('id_tagihan', models.AutoField(primary_key=True, serialize=False)),
                ('periode', models.CharField(max_length=50)),
                ('penggunaan_air', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nominal_tagihan', models.IntegerField()),
                ('tenggat', models.DateField()),
                ('status_tagihan', models.CharField(max_length=20)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagihan', to='AirBersih.user')),
            ],
        ),
        migrations.CreateModel(
            name='Pengaduan',
            fields=[
                ('id_pengaduan', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal_pengaduan', models.DateField()),
                ('jenis_pengaduan', models.CharField(max_length=50)),
                ('isi_pengaduan', models.TextField()),
                ('status_pengaduan', models.CharField(max_length=50)),
                ('tanggapan_petugas', models.TextField()),
                ('id_petugas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengaduan', to='AirBersih.petugas')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengaduan', to='AirBersih.user')),
            ],
        ),
        migrations.CreateModel(
            name='Pembayaran',
            fields=[
                ('id_pembayaran', models.AutoField(primary_key=True, serialize=False)),
                ('nominal_pembayaran', models.IntegerField()),
                ('metode_pembayaran', models.CharField(max_length=50)),
                ('tanggal_pembayaran', models.DateField()),
                ('status_pembayaran', models.CharField(max_length=20)),
                ('id_tagihan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pembayaran', to='AirBersih.tagihan')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pembayaran', to='AirBersih.user')),
            ],
        ),
    ]
