# Generated by Django 5.1.2 on 2024-12-02 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AirBersih', '0002_alter_golonganpelanggan_tarif_0_3_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='MainAdmin',
        ),
    ]
