# Generated by Django 5.1.2 on 2024-12-02 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AirBersih', '0003_rename_admin_mainadmin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MainAdmin',
            new_name='Admin',
        ),
    ]
