# Generated by Django 5.1.2 on 2024-12-02 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AirBersih', '0004_rename_mainadmin_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golonganpelanggan',
            name='tarif_0_3',
            field=models.FloatField(help_text='Dalam rupiah (Rp), untuk penggunaan 0-3 m3'),
        ),
        migrations.AlterField(
            model_name='golonganpelanggan',
            name='tarif_10_20',
            field=models.FloatField(help_text='Dalam rupiah (Rp), untuk penggunaan 10-20 m3'),
        ),
        migrations.AlterField(
            model_name='golonganpelanggan',
            name='tarif_3_10',
            field=models.FloatField(help_text='Dalam rupiah (Rp), untuk penggunaan 3-10 m3'),
        ),
        migrations.AlterField(
            model_name='golonganpelanggan',
            name='tarif_diatas_20',
            field=models.FloatField(help_text='Dalam rupiah (Rp), untuk penggunaan di atas 20 m3'),
        ),
        migrations.AlterField(
            model_name='pembayaran',
            name='nominal_pembayaran',
            field=models.IntegerField(help_text='Dalam rupiah (Rp)'),
        ),
        migrations.AlterField(
            model_name='pembayaran',
            name='status_pembayaran',
            field=models.CharField(choices=[('Prs', 'Diproses'), ('Sls', 'Selesai'), ('Btl', 'Dibatalkan')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pengaduan',
            name='status_pengaduan',
            field=models.CharField(choices=[('Tkr', 'Terkirim'), ('Prs', 'Diproses'), ('Sls', 'Selesai'), ('Btl', 'Dibatalkan')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sumberair',
            name='kapasitas',
            field=models.IntegerField(help_text='Dalam liter per detik (lps)'),
        ),
        migrations.AlterField(
            model_name='sumberair',
            name='status_sumber_air',
            field=models.CharField(choices=[('Atf', 'Aktif'), ('TdkAtf', 'Tidak Aktif')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tagihan',
            name='nominal_tagihan',
            field=models.IntegerField(help_text='Dalam rupiah (Rp)'),
        ),
        migrations.AlterField(
            model_name='tagihan',
            name='penggunaan_air',
            field=models.FloatField(help_text='Penggunaan air dalam m3'),
        ),
        migrations.AlterField(
            model_name='tagihan',
            name='status_tagihan',
            field=models.CharField(choices=[('BlmByr', 'Belum Dibayar'), ('SdhByr', 'Sudah Dibayar')], max_length=20),
        ),
    ]
