# Generated by Django 5.1.2 on 2024-12-03 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AirBersih', '0005_alter_golonganpelanggan_tarif_0_3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sumberair',
            name='jenis',
        ),
    ]
