# Generated by Django 5.1.2 on 2024-12-12 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AirBersih', '0007_rename_admin_airbersihadmin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='golonganpelanggan',
            old_name='kelompok_pelanggan',
            new_name='golongan_pelanggan',
        ),
    ]
