# Generated by Django 5.1.2 on 2024-12-12 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AirBersih', '0008_rename_kelompok_pelanggan_golonganpelanggan_golongan_pelanggan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pengguna',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('nama_pengguna', models.CharField(max_length=50)),
                ('nik_pengguna', models.CharField(max_length=16, unique=True)),
                ('jenis_kelamin_pengguna', models.CharField(choices=[('L', 'Laki-Laki'), ('P', 'Perempuan')], max_length=10)),
                ('alamat_pengguna', models.TextField()),
                ('kecamatan', models.CharField(max_length=50)),
                ('email_pengguna', models.EmailField(max_length=50, unique=True)),
                ('no_telepon_pengguna', models.CharField(max_length=15)),
                ('password_pengguna', models.CharField(max_length=30)),
                ('id_golongan_pelanggan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengguna', to='AirBersih.golonganpelanggan')),
                ('id_lokasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengguna', to='AirBersih.lokasi')),
            ],
        ),
        migrations.AlterField(
            model_name='pembayaran',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pembayaran', to='AirBersih.pengguna'),
        ),
        migrations.AlterField(
            model_name='pengaduan',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengaduan', to='AirBersih.pengguna'),
        ),
        migrations.AlterField(
            model_name='tagihan',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagihan', to='AirBersih.pengguna'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
