# Generated by Django 5.1.2 on 2024-12-12 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AirBersih', '0009_pengguna_alter_pembayaran_id_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pengguna',
            old_name='alamat_pengguna',
            new_name='alamat_user',
        ),
        migrations.RenameField(
            model_name='pengguna',
            old_name='email_pengguna',
            new_name='email_user',
        ),
        migrations.RenameField(
            model_name='pengguna',
            old_name='jenis_kelamin_pengguna',
            new_name='jenis_kelamin_user',
        ),
        migrations.RenameField(
            model_name='pengguna',
            old_name='nama_pengguna',
            new_name='nama_user',
        ),
        migrations.RenameField(
            model_name='pengguna',
            old_name='nik_pengguna',
            new_name='nik_user',
        ),
        migrations.RenameField(
            model_name='pengguna',
            old_name='no_telepon_pengguna',
            new_name='no_telepon_user',
        ),
        migrations.RenameField(
            model_name='pengguna',
            old_name='password_pengguna',
            new_name='password_user',
        ),
        migrations.AlterField(
            model_name='pengguna',
            name='id_golongan_pelanggan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='AirBersih.golonganpelanggan'),
        ),
        migrations.AlterField(
            model_name='pengguna',
            name='id_lokasi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='AirBersih.lokasi'),
        ),
    ]
